version: '3.8'

services:
  # Service base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: zombieland-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: zombieland
      POSTGRES_PASSWORD: zombieland
      POSTGRES_DB: zombieland
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Port standard de PostgreSQL
    networks:
      - zombieland-network

  # Service backend (API)
  backend:
    build:
      context: ./ZombieLand-back
      dockerfile: Dockerfile
    container_name: zombieland-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PORT=3666
      - PG_URL=postgres://zombieland:zombieland@postgres:5432/zombieland
      - JWT_SECRET=your_jwt_secret_here
      - SESSION_SECRET=your_session_secret_here
      - MAIL=your_mail_here
      - MAIL_PASSWORD=your_mail_password_here
      - FRONT_URL=http://localhost:666
      - BACK_URL=http://localhost:3666/
      - VITE_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=your_stripe_key_here
      - VITE_NEXT_PUBLIC_STRIPE_PRICE_ID=your_stripe_price_id_here
    ports:
      - "3666:3666"
    volumes:
      - ./ZombieLand-back:/app
      - /app/node_modules
    networks:
      - zombieland-network
    command: >
      sh -c "npm run db:reset && PORT=3666 npm run dev"

  # Service frontend
  frontend:
    build:
      context: ./ZombieLand-front
      dockerfile: Dockerfile
    container_name: zombieland-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3666
      - VITE_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=your_stripe_key_here
      - VITE_NEXT_PUBLIC_STRIPE_PRICE_ID=your_stripe_price_id_here
    ports:
      - "666:5173"  # Map le port 666 externe au port 5173 interne (port de Vite)
    volumes:
      - ./ZombieLand-front:/app
      - /app/node_modules
    networks:
      - zombieland-network

networks:
  zombieland-network:
    driver: bridge

volumes:
  postgres-data:
