services:
  # Service base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: zombieland-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: zombieland
      POSTGRES_PASSWORD: zombieland
      POSTGRES_DB: zombieland
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Port standard de PostgreSQL
    networks:
      - zombieland-network
      
  # Service backend (API)
  backend:
    build:
      context: ./ZombieLand-back
      dockerfile: Dockerfile
    container_name: zombieland-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PORT=3666
      - PG_URL=postgres://zombieland:zombieland@postgres:5432/zombieland
      - JWT_SECRET=your_jwt_secret_here
      - SESSION_SECRET=your_session_secret_here
      - MAIL=your_mail_here
      - MAIL_PASSWORD=your_mail_password_here
      - FRONT_URL=https://zombieland.creachtheo.fr  # Modifié pour HTTPS
      - BACK_URL=https://api.zombieland.creachtheo.fr/  # Modifié pour HTTPS
      - VITE_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=your_stripe_key_here
      - VITE_NEXT_PUBLIC_STRIPE_PRICE_ID=your_stripe_price_id_here
    expose:
      - "3666"  # Exposé au réseau interne uniquement
    volumes:
      - ./ZombieLand-back:/app
      - /app/node_modules
    networks:
      - zombieland-network
      - traefik-public
    command: >
      sh -c "npm run db:reset && PORT=3666 npm run dev"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zombieland-backend.rule=Host(`api.zombieland.creachtheo.fr`)"
      - "traefik.http.routers.zombieland-backend.entrypoints=websecure"
      - "traefik.http.routers.zombieland-backend.tls=true"
      - "traefik.http.routers.zombieland-backend.tls.certresolver=myresolver"
      - "traefik.http.services.zombieland-backend.loadbalancer.server.port=3666"
      
  # Service frontend
  frontend:
    build:
      context: ./ZombieLand-front
      dockerfile: Dockerfile
    container_name: zombieland-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_API_URL=https://api.zombieland.creachtheo.fr  # Modifié pour HTTPS
      - VITE_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=your_stripe_key_here
      - VITE_NEXT_PUBLIC_STRIPE_PRICE_ID=your_stripe_price_id_here
    expose:
      - "5173"  # Exposé au réseau interne uniquement
    volumes:
      - ./ZombieLand-front:/app
      - /app/node_modules
    networks:
      - zombieland-network
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zombieland-frontend.rule=Host(`zombieland.creachtheo.fr`)"
      - "traefik.http.routers.zombieland-frontend.entrypoints=websecure"
      - "traefik.http.routers.zombieland-frontend.tls=true"
      - "traefik.http.routers.zombieland-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.zombieland-frontend.loadbalancer.server.port=5173"

networks:
  zombieland-network:
    driver: bridge
  traefik-public:
    external: true  # Utilise le réseau Traefik existant
    
volumes:
  postgres-data:
